cwlVersion: v1.2
class: CommandLineTool
id: coyote_stats2json
doc: "Convert stats files generated by gatk or samtools into json format."
requirements:
  - class: InlineJavascriptRequirement
  - class: ShellCommandRequirement
  - class: DockerRequirement
    dockerPull: 'python:3.7.2'
  - class: ResourceRequirement
    ramMin: $(inputs.ram*1000)
    coresMin: $(inputs.cpu)
  - class: InitialWorkDirRequirement
    listing:
    - entryname: samStats2json_3a90a2f.py
      writable: false
      entry:
        $include: ../scripts/samStats2json_3a90a2f.py
baseCommand: [python, samStats2json_3a90a2f.py]
inputs:
  # Required Arguments
  output: { type: 'string', inputBinding: { position: 2, prefix: "--output"}, doc: "string name to use for output file" }
  statfile: { type: 'File', inputBinding: { position: 8 }, doc: "the file that will be converted to json format" }
  filetype: { type: 'string', inputBinding: { position: 9 }, doc: "the file type that will be imported" }

  # Optional Arguments
  samplename: { type: 'string?', inputBinding: { position: 2, prefix: "--samplename"}, doc: "accumulated stats at the sample level" }
  libraryname: { type: 'string?', inputBinding: { position: 2, prefix: "--libraryname"}, doc: "accumulated stats at the library level, requires sample name arguments" }
  readgroupname: { type: 'string?', inputBinding: { position: 2, prefix: "--readgroupname"}, doc: "accumulated stats at the readgroup level, requires library and sample arguments" }

  cpu:
    type: 'int?'
    default: 1
    doc: "Number of CPUs to allocate to this task."
  ram:
    type: 'int?'
    default: 4
    doc: "GB size of RAM to allocate to this task."
outputs:
  output: 
    type: File
    outputBinding:
      glob: $(inputs.output) 
